<a href="https://colab.research.google.com/github/ingridevv/data-engineering-zoomcamp/blob/main/week_6_batch/3_groupby_joins.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preparing Yellow and Green Taxi Data

In [1]:
%%writefile download_data.sh
set -e

TAXI_TYPE=$1 # "yellow"
YEAR=$2 # 2020

URL_PREFIX="https://github.com/DataTalksClub/nyc-tlc-data/releases/download"

for MONTH in {1..12}; do
  FMONTH=`printf "%02d" ${MONTH}`

  URL="${URL_PREFIX}/${TAXI_TYPE}/${TAXI_TYPE}_tripdata_${YEAR}-${FMONTH}.csv.gz"

  LOCAL_PREFIX="data/raw/${TAXI_TYPE}/${YEAR}/${FMONTH}"
  LOCAL_FILE="${TAXI_TYPE}_tripdata_${YEAR}_${FMONTH}.csv.gz"
  LOCAL_PATH="${LOCAL_PREFIX}/${LOCAL_FILE}"

  echo "downloading ${URL} to ${LOCAL_PATH}"
  mkdir -p ${LOCAL_PREFIX}
  wget ${URL} -O ${LOCAL_PATH}

done

Writing download_data.sh

In [2]:
!chmod +x download_data.sh

In [3]:
# Download yellow taxi data 2020
!./download_data.sh yellow 2020

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-01.csv.gz to data/raw/yellow/2020/01/yellow_tripdata_2020_01.csv.gz
--2026-03-08 14:03:48--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-01.csv.gz
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/1bc3de9c-af03-46e3-baa6-c4475782682d?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A03%3A07Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-01.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A03%3A05Z&ske=2026-03-08T15%3A03%3A07Z&sks=b&skv=2018-11-09&sig=L2ECJKFnQK9ObaJjhZ79a%2Brh8kc4xSGa%2Fw39jcxZ9CU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MjIyOCwibmJmIjoxNzcyOTc4NjI4LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.wQn8X1yLk-5A6GdRRK12lo5cdhXE9RadcG0HmnJi7D4&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-01.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:03:48--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/1bc3de9c-af03-46e3-baa6-c4475782682d?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A03%3A07Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-01.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A03%3A05Z&ske=2026-03-08T15%3A03%3A07Z&sks=b&skv=2018-11-09&sig=L2ECJKFnQK9ObaJjhZ79a%2Brh8kc4xSGa%2Fw39jcxZ9CU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MjIyOCwibmJmIjoxNzcyOTc4NjI4LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.wQn8X1yLk-5A6GdRRK12lo5cdhXE9RadcG0HmnJi7D4&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-01.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 116338814 (111M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2020/01/yellow_tripdata_2020_01.csv.gz’

data/raw/yellow/202 100%[===================>] 110.95M  40.0MB/s    in 2.8s

2026-03-08 14:03:51 (40.0 MB/s) - ‘data/raw/yellow/2020/01/yellow_tripdata_2020_01.csv.gz’ saved [116338814/116338814]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-02.csv.gz to data/raw/yellow/2020/02/yellow_tripdata_2020_02.csv.gz
--2026-03-08 14:03:51--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-02.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/fdaae067-f8d4-4f9b-9e45-2e760539d309?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A00%3A51Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-02.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A00%3A19Z&ske=2026-03-08T15%3A00%3A51Z&sks=b&skv=2018-11-09&sig=e1C7BM1%2FeRi4R215jbGpi2W7wqfhlOXXnMHtqFX17BE%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MjIzMSwibmJmIjoxNzcyOTc4NjMxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.bkhbd6fKJlbXW4w8N0QrniUrnhINcSZCuN9cVupCIcQ&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-02.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:03:51--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/fdaae067-f8d4-4f9b-9e45-2e760539d309?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A00%3A51Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-02.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A00%3A19Z&ske=2026-03-08T15%3A00%3A51Z&sks=b&skv=2018-11-09&sig=e1C7BM1%2FeRi4R215jbGpi2W7wqfhlOXXnMHtqFX17BE%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MjIzMSwibmJmIjoxNzcyOTc4NjMxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.bkhbd6fKJlbXW4w8N0QrniUrnhINcSZCuN9cVupCIcQ&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-02.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 114701110 (109M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2020/02/yellow_tripdata_2020_02.csv.gz’

data/raw/yellow/202 100%[===================>] 109.39M  38.8MB/s    in 2.8s

2026-03-08 14:03:54 (38.8 MB/s) - ‘data/raw/yellow/2020/02/yellow_tripdata_2020_02.csv.gz’ saved [114701110/114701110]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-03.csv.gz to data/raw/yellow/2020/03/yellow_tripdata_2020_03.csv.gz
--2026-03-08 14:03:54--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-03.csv.gz
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/46d9461c-89fe-4084-a06f-92256b7e035c?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A38%3A48Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-03.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A38%3A23Z&ske=2026-03-08T14%3A38%3A48Z&sks=b&skv=2018-11-09&sig=vm0vi6rEg03RfQOTQVgwBW10oJB7bDTu%2FvGz%2Fy1F%2BGg%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQzNCwibmJmIjoxNzcyOTc4NjM0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.H1ES5rAxPhSutXDPWaCFPEende8xtdZDPi5ODvjKt14&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-03.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:03:54--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/46d9461c-89fe-4084-a06f-92256b7e035c?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A38%3A48Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-03.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A38%3A23Z&ske=2026-03-08T14%3A38%3A48Z&sks=b&skv=2018-11-09&sig=vm0vi6rEg03RfQOTQVgwBW10oJB7bDTu%2FvGz%2Fy1F%2BGg%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQzNCwibmJmIjoxNzcyOTc4NjM0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.H1ES5rAxPhSutXDPWaCFPEende8xtdZDPi5ODvjKt14&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-03.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55004095 (52M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2020/03/yellow_tripdata_2020_03.csv.gz’

data/raw/yellow/202 100%[===================>]  52.46M  54.4MB/s    in 1.0s

2026-03-08 14:03:55 (54.4 MB/s) - ‘data/raw/yellow/2020/03/yellow_tripdata_2020_03.csv.gz’ saved [55004095/55004095]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-04.csv.gz to data/raw/yellow/2020/04/yellow_tripdata_2020_04.csv.gz
--2026-03-08 14:03:55--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-04.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/3a5b385e-7c0e-40bc-a73e-ae68a584a73a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A46%3A42Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-04.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A46%3A07Z&ske=2026-03-08T14%3A46%3A42Z&sks=b&skv=2018-11-09&sig=wtO0fiL4EnvjE9yjmqzim4Aq%2BFOElkW2wHY1yWZ%2Bl9w%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODkzNSwibmJmIjoxNzcyOTc4NjM1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.H7DcE-BhYeUgrJIoduX1fPTnBTdKU18VG14nG_3VNDw&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-04.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:03:55--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/3a5b385e-7c0e-40bc-a73e-ae68a584a73a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A46%3A42Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-04.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A46%3A07Z&ske=2026-03-08T14%3A46%3A42Z&sks=b&skv=2018-11-09&sig=wtO0fiL4EnvjE9yjmqzim4Aq%2BFOElkW2wHY1yWZ%2Bl9w%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODkzNSwibmJmIjoxNzcyOTc4NjM1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.H7DcE-BhYeUgrJIoduX1fPTnBTdKU18VG14nG_3VNDw&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-04.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4429528 (4.2M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2020/04/yellow_tripdata_2020_04.csv.gz’

data/raw/yellow/202 100%[===================>]   4.22M  --.-KB/s    in 0.05s

2026-03-08 14:03:56 (86.4 MB/s) - ‘data/raw/yellow/2020/04/yellow_tripdata_2020_04.csv.gz’ saved [4429528/4429528]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-05.csv.gz to data/raw/yellow/2020/05/yellow_tripdata_2020_05.csv.gz
--2026-03-08 14:03:56--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-05.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/7c737dbd-a617-477c-9b86-a939e917baa8?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A02%3A27Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-05.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A01%3A58Z&ske=2026-03-08T15%3A02%3A27Z&sks=b&skv=2018-11-09&sig=0dfjbILpIgifbF%2FK%2Fz6QoMBQUjtz1UX1MlvovjFEKoU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODkzNiwibmJmIjoxNzcyOTc4NjM2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.py-kc_B0nxlkMzi7Q-rCucgSfPgvIpb6eLdry4HHPqE&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-05.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:03:56--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/7c737dbd-a617-477c-9b86-a939e917baa8?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A02%3A27Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-05.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A01%3A58Z&ske=2026-03-08T15%3A02%3A27Z&sks=b&skv=2018-11-09&sig=0dfjbILpIgifbF%2FK%2Fz6QoMBQUjtz1UX1MlvovjFEKoU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODkzNiwibmJmIjoxNzcyOTc4NjM2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.py-kc_B0nxlkMzi7Q-rCucgSfPgvIpb6eLdry4HHPqE&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-05.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6528512 (6.2M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2020/05/yellow_tripdata_2020_05.csv.gz’

data/raw/yellow/202 100%[===================>]   6.23M  --.-KB/s    in 0.1s

2026-03-08 14:03:56 (49.0 MB/s) - ‘data/raw/yellow/2020/05/yellow_tripdata_2020_05.csv.gz’ saved [6528512/6528512]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-06.csv.gz to data/raw/yellow/2020/06/yellow_tripdata_2020_06.csv.gz
--2026-03-08 14:03:56--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-06.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/426b9080-186a-40fe-873a-d8019bf00e9a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A56%3A07Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-06.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A56%3A00Z&ske=2026-03-08T14%3A56%3A07Z&sks=b&skv=2018-11-09&sig=Qf%2FL%2Fzzf2FHCTOo8x97NIcxE5NCIylfZ5gsefJuNEO4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODkzNiwibmJmIjoxNzcyOTc4NjM2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.py-kc_B0nxlkMzi7Q-rCucgSfPgvIpb6eLdry4HHPqE&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-06.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:03:56--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/426b9080-186a-40fe-873a-d8019bf00e9a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A56%3A07Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-06.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A56%3A00Z&ske=2026-03-08T14%3A56%3A07Z&sks=b&skv=2018-11-09&sig=Qf%2FL%2Fzzf2FHCTOo8x97NIcxE5NCIylfZ5gsefJuNEO4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODkzNiwibmJmIjoxNzcyOTc4NjM2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.py-kc_B0nxlkMzi7Q-rCucgSfPgvIpb6eLdry4HHPqE&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-06.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10206684 (9.7M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2020/06/yellow_tripdata_2020_06.csv.gz’

data/raw/yellow/202 100%[===================>]   9.73M  --.-KB/s    in 0.1s

2026-03-08 14:03:56 (87.3 MB/s) - ‘data/raw/yellow/2020/06/yellow_tripdata_2020_06.csv.gz’ saved [10206684/10206684]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-07.csv.gz to data/raw/yellow/2020/07/yellow_tripdata_2020_07.csv.gz
--2026-03-08 14:03:56--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2020-07.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/1d635856-7182-4a46-a5a0-19b4e158fe1d?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A58%3A35Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2020-07.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A58%3A27Z&ske=2026-03-08T14%3A58%3A35Z&sks=b&skv=2018-11-09&sig=Qzdgx6ZHPvpu3SSnlzCmrME72eN9tPKcUiPsxXg%2FNRw%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQzNywibmJmIjoxNzcyOTc4NjM3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.rGeqtdcA41s8u_L08Gad0s65MZF7Dop6R0l9KahdNDw&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2020-07.csv.gz&response-content-type=application%2Foctet-stream [following]

In [4]:
!ls data/raw/yellow/2020/01

yellow_tripdata_2020_01.csv.gz

In [5]:
# Download yellow taxi data 2021
!./download_data.sh yellow 2021

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz to data/raw/yellow/2021/01/yellow_tripdata_2021_01.csv.gz
--2026-03-08 14:04:02--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/f6895842-79e6-4a43-9458-e5b0b454a340?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A51%3A48Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-01.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A51%3A29Z&ske=2026-03-08T14%3A51%3A48Z&sks=b&skv=2018-11-09&sig=LYPL%2FwlLsB%2Bz%2FHaUY%2FMN2mQdX%2BZURO8SYyQglO1vyiY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0MiwibmJmIjoxNzcyOTc4NjQyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.BpIEpEL8uXcx_aY4e1gOrdCdZd1I9tQNQYyZV62nJLg&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-01.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:02--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/f6895842-79e6-4a43-9458-e5b0b454a340?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A51%3A48Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-01.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A51%3A29Z&ske=2026-03-08T14%3A51%3A48Z&sks=b&skv=2018-11-09&sig=LYPL%2FwlLsB%2Bz%2FHaUY%2FMN2mQdX%2BZURO8SYyQglO1vyiY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0MiwibmJmIjoxNzcyOTc4NjQyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.BpIEpEL8uXcx_aY4e1gOrdCdZd1I9tQNQYyZV62nJLg&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-01.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25031880 (24M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2021/01/yellow_tripdata_2021_01.csv.gz’

data/raw/yellow/202 100%[===================>]  23.87M   118MB/s    in 0.2s

2026-03-08 14:04:02 (118 MB/s) - ‘data/raw/yellow/2021/01/yellow_tripdata_2021_01.csv.gz’ saved [25031880/25031880]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-02.csv.gz to data/raw/yellow/2021/02/yellow_tripdata_2021_02.csv.gz
--2026-03-08 14:04:02--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-02.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/146b26ce-6d6f-451c-886e-750423d5d2d6?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A45%3A06Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-02.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A44%3A39Z&ske=2026-03-08T14%3A45%3A06Z&sks=b&skv=2018-11-09&sig=qBDtZ%2FtTdOb86%2BFBS2LTobe2WrtNOyBDW%2FQuCL2as4c%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0MiwibmJmIjoxNzcyOTc4NjQyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.BpIEpEL8uXcx_aY4e1gOrdCdZd1I9tQNQYyZV62nJLg&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-02.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:02--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/146b26ce-6d6f-451c-886e-750423d5d2d6?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A45%3A06Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-02.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A44%3A39Z&ske=2026-03-08T14%3A45%3A06Z&sks=b&skv=2018-11-09&sig=qBDtZ%2FtTdOb86%2BFBS2LTobe2WrtNOyBDW%2FQuCL2as4c%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0MiwibmJmIjoxNzcyOTc4NjQyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.BpIEpEL8uXcx_aY4e1gOrdCdZd1I9tQNQYyZV62nJLg&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-02.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25096821 (24M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2021/02/yellow_tripdata_2021_02.csv.gz’

data/raw/yellow/202 100%[===================>]  23.93M  31.9MB/s    in 0.8s

2026-03-08 14:04:03 (31.9 MB/s) - ‘data/raw/yellow/2021/02/yellow_tripdata_2021_02.csv.gz’ saved [25096821/25096821]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-03.csv.gz to data/raw/yellow/2021/03/yellow_tripdata_2021_03.csv.gz
--2026-03-08 14:04:03--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-03.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/0b7041e8-cd8f-414d-839f-729b7a58db25?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A47%3A32Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-03.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A47%3A20Z&ske=2026-03-08T14%3A47%3A32Z&sks=b&skv=2018-11-09&sig=zHpGXfn1Qj2MFM57G%2Fi1pkD227MzA7rIsgTLYLzoULQ%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0MywibmJmIjoxNzcyOTc4NjQzLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.3Ueb0qDPECFdma5ycztmkun0YXrpTqnwr3ITF7GojuA&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-03.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:03--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/0b7041e8-cd8f-414d-839f-729b7a58db25?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A47%3A32Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-03.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A47%3A20Z&ske=2026-03-08T14%3A47%3A32Z&sks=b&skv=2018-11-09&sig=zHpGXfn1Qj2MFM57G%2Fi1pkD227MzA7rIsgTLYLzoULQ%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0MywibmJmIjoxNzcyOTc4NjQzLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.3Ueb0qDPECFdma5ycztmkun0YXrpTqnwr3ITF7GojuA&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-03.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35196823 (34M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2021/03/yellow_tripdata_2021_03.csv.gz’

data/raw/yellow/202 100%[===================>]  33.57M  54.8MB/s    in 0.6s

2026-03-08 14:04:04 (54.8 MB/s) - ‘data/raw/yellow/2021/03/yellow_tripdata_2021_03.csv.gz’ saved [35196823/35196823]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-04.csv.gz to data/raw/yellow/2021/04/yellow_tripdata_2021_04.csv.gz
--2026-03-08 14:04:04--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-04.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/bc2b82bc-f1b6-4624-8b2f-756cbc985ee3?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A37%3A43Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-04.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A36%3A52Z&ske=2026-03-08T14%3A37%3A43Z&sks=b&skv=2018-11-09&sig=ugp3VR6gvdwYP8tA9d26TRSk2E7oqiw4JBlpkdlbNLY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0NCwibmJmIjoxNzcyOTc4NjQ0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Jvuauwrog-1JyvhgeHNeawUIBqYDrRDy4k8HgkROjvA&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-04.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:04--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/bc2b82bc-f1b6-4624-8b2f-756cbc985ee3?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A37%3A43Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-04.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A36%3A52Z&ske=2026-03-08T14%3A37%3A43Z&sks=b&skv=2018-11-09&sig=ugp3VR6gvdwYP8tA9d26TRSk2E7oqiw4JBlpkdlbNLY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0NCwibmJmIjoxNzcyOTc4NjQ0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Jvuauwrog-1JyvhgeHNeawUIBqYDrRDy4k8HgkROjvA&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-04.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39942590 (38M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2021/04/yellow_tripdata_2021_04.csv.gz’

data/raw/yellow/202 100%[===================>]  38.09M  77.2MB/s    in 0.5s

2026-03-08 14:04:05 (77.2 MB/s) - ‘data/raw/yellow/2021/04/yellow_tripdata_2021_04.csv.gz’ saved [39942590/39942590]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-05.csv.gz to data/raw/yellow/2021/05/yellow_tripdata_2021_05.csv.gz
--2026-03-08 14:04:05--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-05.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/f0b49896-0d39-40b9-b89b-350718f253f3?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A48%3A19Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-05.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A47%3A32Z&ske=2026-03-08T14%3A48%3A19Z&sks=b&skv=2018-11-09&sig=MIValTqb%2F5PhKbYJlzc2HJiYlz2BkGQQOpVGiVkAE%2BY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0NSwibmJmIjoxNzcyOTc4NjQ1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.u-o1PpGdLHyrzeBTp9_AJbUNqBnwsQJsRB0N7ITM7Y0&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-05.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:05--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/f0b49896-0d39-40b9-b89b-350718f253f3?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A48%3A19Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-05.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A47%3A32Z&ske=2026-03-08T14%3A48%3A19Z&sks=b&skv=2018-11-09&sig=MIValTqb%2F5PhKbYJlzc2HJiYlz2BkGQQOpVGiVkAE%2BY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0NSwibmJmIjoxNzcyOTc4NjQ1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.u-o1PpGdLHyrzeBTp9_AJbUNqBnwsQJsRB0N7ITM7Y0&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-05.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 46300675 (44M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2021/05/yellow_tripdata_2021_05.csv.gz’

data/raw/yellow/202 100%[===================>]  44.16M  29.3MB/s    in 1.5s

2026-03-08 14:04:07 (29.3 MB/s) - ‘data/raw/yellow/2021/05/yellow_tripdata_2021_05.csv.gz’ saved [46300675/46300675]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-06.csv.gz to data/raw/yellow/2021/06/yellow_tripdata_2021_06.csv.gz
--2026-03-08 14:04:07--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-06.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/d74c9b25-23a3-45f6-983d-d5bb7a36f590?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A02%3A54Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-06.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A02%3A28Z&ske=2026-03-08T15%3A02%3A54Z&sks=b&skv=2018-11-09&sig=I8aQ61G5yf9b8egGyILwoDIQ3Fqa7WqSWOvU9W8dAwk%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0NywibmJmIjoxNzcyOTc4NjQ3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Dl1D2eVdJLgmOpwPfyxs0V8sHXn8ZaOHwGsfM5gm6m4&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-06.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:07--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/d74c9b25-23a3-45f6-983d-d5bb7a36f590?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A02%3A54Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-06.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A02%3A28Z&ske=2026-03-08T15%3A02%3A54Z&sks=b&skv=2018-11-09&sig=I8aQ61G5yf9b8egGyILwoDIQ3Fqa7WqSWOvU9W8dAwk%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0NywibmJmIjoxNzcyOTc4NjQ3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Dl1D2eVdJLgmOpwPfyxs0V8sHXn8ZaOHwGsfM5gm6m4&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-06.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52500930 (50M) [application/octet-stream]
Saving to: ‘data/raw/yellow/2021/06/yellow_tripdata_2021_06.csv.gz’

data/raw/yellow/202 100%[===================>]  50.07M  46.8MB/s    in 1.1s

2026-03-08 14:04:08 (46.8 MB/s) - ‘data/raw/yellow/2021/06/yellow_tripdata_2021_06.csv.gz’ saved [52500930/52500930]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-07.csv.gz to data/raw/yellow/2021/07/yellow_tripdata_2021_07.csv.gz
--2026-03-08 14:04:08--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-07.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/3db08a32-d2ce-4066-866b-76b7ce1034e2?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A48%3A13Z&rscd=attachment%3B+filename%3Dyellow_tripdata_2021-07.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A47%3A40Z&ske=2026-03-08T14%3A48%3A13Z&sks=b&skv=2018-11-09&sig=JIEp4s49owmlILSE2p6pIp1NzlHBBkVwAEJ0ZtG%2B4Zc%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MDQ0OCwibmJmIjoxNzcyOTc4NjQ4LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.JPjIuALvJOMOsMx0FI2hLurpOkukO8cJ1lM1lgyR9Bk&response-content-disposition=attachment%3B%20filename%3Dyellow_tripdata_2021-07.csv.gz&response-content-type=application%2Foctet-stream [following]

In [6]:
!zcat data/raw/yellow/2020/01/yellow_tripdata_2020_01.csv.gz | head -n 10

VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
1,2020-01-01 00:28:15,2020-01-01 00:33:03,1,1.20,1,N,238,239,1,6,3,0.5,1.47,0,0.3,11.27,2.5
1,2020-01-01 00:35:39,2020-01-01 00:43:04,1,1.20,1,N,239,238,1,7,3,0.5,1.5,0,0.3,12.3,2.5
1,2020-01-01 00:47:41,2020-01-01 00:53:52,1,.60,1,N,238,238,1,6,3,0.5,1,0,0.3,10.8,2.5
1,2020-01-01 00:55:23,2020-01-01 01:00:14,1,.80,1,N,238,151,1,5.5,0.5,0.5,1.36,0,0.3,8.16,0
2,2020-01-01 00:01:58,2020-01-01 00:04:16,1,.00,1,N,193,193,2,3.5,0.5,0.5,0,0,0.3,4.8,0
2,2020-01-01 00:09:44,2020-01-01 00:10:37,1,.03,1,N,7,193,2,2.5,0.5,0.5,0,0,0.3,3.8,0
2,2020-01-01 00:39:25,2020-01-01 00:39:29,1,.00,1,N,193,193,1,2.5,0.5,0.5,0.01,0,0.3,3.81,0
2,2019-12-18 15:27:49,2019-12-18 15:28:59,1,.00,5,N,193,193,1,0.01,0,0,0,0,0.3,2.81,2.5
2,2019-12-18 15:30:35,2019-12-18 15:31:35,4,.00,1,N,193,193,1,2.5,0.5,0.5,0,0,0.3,6.3,2.5

In [7]:
! ./download_data.sh green 2020

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-01.csv.gz to data/raw/green/2020/01/green_tripdata_2020_01.csv.gz
--2026-03-08 14:04:10--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-01.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/6e8a7b28-b1ea-455e-9803-cd8943d96c26?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A50%3A38Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-01.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A50%3A06Z&ske=2026-03-08T14%3A50%3A38Z&sks=b&skv=2018-11-09&sig=bmLykUtJkW2%2B0lFNuHdOIjd41Xcq44IZoW3iXUOC%2B9c%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MCwibmJmIjoxNzcyOTc4NjUwLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.qsgY6EJmTzK1xMsBarefsK_YZZ4GY-bLrWUcpFFnuNg&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-01.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:10--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/6e8a7b28-b1ea-455e-9803-cd8943d96c26?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A50%3A38Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-01.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A50%3A06Z&ske=2026-03-08T14%3A50%3A38Z&sks=b&skv=2018-11-09&sig=bmLykUtJkW2%2B0lFNuHdOIjd41Xcq44IZoW3iXUOC%2B9c%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MCwibmJmIjoxNzcyOTc4NjUwLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.qsgY6EJmTzK1xMsBarefsK_YZZ4GY-bLrWUcpFFnuNg&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-01.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7541109 (7.2M) [application/octet-stream]
Saving to: ‘data/raw/green/2020/01/green_tripdata_2020_01.csv.gz’

data/raw/green/2020 100%[===================>]   7.19M  --.-KB/s    in 0.08s

2026-03-08 14:04:10 (94.7 MB/s) - ‘data/raw/green/2020/01/green_tripdata_2020_01.csv.gz’ saved [7541109/7541109]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-02.csv.gz to data/raw/green/2020/02/green_tripdata_2020_02.csv.gz
--2026-03-08 14:04:10--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-02.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/a044ac3e-1cf9-4cc5-ba7b-a96aeee93065?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A41%3A04Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-02.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A40%3A47Z&ske=2026-03-08T14%3A41%3A04Z&sks=b&skv=2018-11-09&sig=%2FJRilME%2BDgc0K2NogRsflQs%2Fwb%2BcovyRzhdXQDhfhW4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MCwibmJmIjoxNzcyOTc4NjUwLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.qsgY6EJmTzK1xMsBarefsK_YZZ4GY-bLrWUcpFFnuNg&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-02.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:10--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/a044ac3e-1cf9-4cc5-ba7b-a96aeee93065?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A41%3A04Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-02.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A40%3A47Z&ske=2026-03-08T14%3A41%3A04Z&sks=b&skv=2018-11-09&sig=%2FJRilME%2BDgc0K2NogRsflQs%2Fwb%2BcovyRzhdXQDhfhW4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MCwibmJmIjoxNzcyOTc4NjUwLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.qsgY6EJmTzK1xMsBarefsK_YZZ4GY-bLrWUcpFFnuNg&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-02.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6891456 (6.6M) [application/octet-stream]
Saving to: ‘data/raw/green/2020/02/green_tripdata_2020_02.csv.gz’

data/raw/green/2020 100%[===================>]   6.57M  --.-KB/s    in 0.07s

2026-03-08 14:04:11 (90.3 MB/s) - ‘data/raw/green/2020/02/green_tripdata_2020_02.csv.gz’ saved [6891456/6891456]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-03.csv.gz to data/raw/green/2020/03/green_tripdata_2020_03.csv.gz
--2026-03-08 14:04:11--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-03.csv.gz
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/3bfdeae7-452d-464e-bf2e-ad862ec2b4c4?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A40%3A50Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-03.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A40%3A10Z&ske=2026-03-08T14%3A40%3A50Z&sks=b&skv=2018-11-09&sig=ZZ%2BUWO9p%2F1550OkJGe5wdLeeiBXcj4Rk084ZTy2Q6Oo%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MSwibmJmIjoxNzcyOTc4NjUxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Ae7eS240U9BH6F2X3KgEEdZFJe6AU5q4L1bWYOyOCg4&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-03.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:11--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/3bfdeae7-452d-464e-bf2e-ad862ec2b4c4?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A40%3A50Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-03.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A40%3A10Z&ske=2026-03-08T14%3A40%3A50Z&sks=b&skv=2018-11-09&sig=ZZ%2BUWO9p%2F1550OkJGe5wdLeeiBXcj4Rk084ZTy2Q6Oo%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MSwibmJmIjoxNzcyOTc4NjUxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Ae7eS240U9BH6F2X3KgEEdZFJe6AU5q4L1bWYOyOCg4&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-03.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3917763 (3.7M) [application/octet-stream]
Saving to: ‘data/raw/green/2020/03/green_tripdata_2020_03.csv.gz’

data/raw/green/2020 100%[===================>]   3.74M  --.-KB/s    in 0.07s

2026-03-08 14:04:11 (57.3 MB/s) - ‘data/raw/green/2020/03/green_tripdata_2020_03.csv.gz’ saved [3917763/3917763]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-04.csv.gz to data/raw/green/2020/04/green_tripdata_2020_04.csv.gz
--2026-03-08 14:04:11--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-04.csv.gz
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/0e20267a-998f-477e-b7c2-2ae0b1e7a57d?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A39%3A34Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-04.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A38%3A53Z&ske=2026-03-08T14%3A39%3A34Z&sks=b&skv=2018-11-09&sig=hwHVhV2rV1xTAlKe8fU6XXB%2BfLPrDP1HBoKfoglnpIM%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MSwibmJmIjoxNzcyOTc4NjUxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Ae7eS240U9BH6F2X3KgEEdZFJe6AU5q4L1bWYOyOCg4&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-04.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:11--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/0e20267a-998f-477e-b7c2-2ae0b1e7a57d?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A39%3A34Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-04.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A38%3A53Z&ske=2026-03-08T14%3A39%3A34Z&sks=b&skv=2018-11-09&sig=hwHVhV2rV1xTAlKe8fU6XXB%2BfLPrDP1HBoKfoglnpIM%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MSwibmJmIjoxNzcyOTc4NjUxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Ae7eS240U9BH6F2X3KgEEdZFJe6AU5q4L1bWYOyOCg4&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-04.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 670357 (655K) [application/octet-stream]
Saving to: ‘data/raw/green/2020/04/green_tripdata_2020_04.csv.gz’

data/raw/green/2020 100%[===================>] 654.65K  --.-KB/s    in 0.03s

2026-03-08 14:04:11 (24.9 MB/s) - ‘data/raw/green/2020/04/green_tripdata_2020_04.csv.gz’ saved [670357/670357]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-05.csv.gz to data/raw/green/2020/05/green_tripdata_2020_05.csv.gz
--2026-03-08 14:04:11--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-05.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/4240fe6d-faf9-4c63-bb74-6a872d228fb8?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A03%3A58Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-05.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A03%3A21Z&ske=2026-03-08T15%3A03%3A58Z&sks=b&skv=2018-11-09&sig=1Ed%2FKm%2FvoDgCVlFGLs5p0B9hFBRHsHiOsS9kkhWe5O8%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MiwibmJmIjoxNzcyOTc4NjUyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.vhgXv3UtQKCYOJpRlpYMGGARRGa2FgYn5HyjSdxiUd0&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-05.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:12--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/4240fe6d-faf9-4c63-bb74-6a872d228fb8?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A03%3A58Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-05.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A03%3A21Z&ske=2026-03-08T15%3A03%3A58Z&sks=b&skv=2018-11-09&sig=1Ed%2FKm%2FvoDgCVlFGLs5p0B9hFBRHsHiOsS9kkhWe5O8%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MiwibmJmIjoxNzcyOTc4NjUyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.vhgXv3UtQKCYOJpRlpYMGGARRGa2FgYn5HyjSdxiUd0&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-05.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1064127 (1.0M) [application/octet-stream]
Saving to: ‘data/raw/green/2020/05/green_tripdata_2020_05.csv.gz’

data/raw/green/2020 100%[===================>]   1.01M  --.-KB/s    in 0.03s

2026-03-08 14:04:12 (31.4 MB/s) - ‘data/raw/green/2020/05/green_tripdata_2020_05.csv.gz’ saved [1064127/1064127]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-06.csv.gz to data/raw/green/2020/06/green_tripdata_2020_06.csv.gz
--2026-03-08 14:04:12--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-06.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/87581eb0-de76-4112-9083-604df873c217?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A03%3A58Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-06.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A03%3A51Z&ske=2026-03-08T15%3A03%3A58Z&sks=b&skv=2018-11-09&sig=4xu2vgxN%2BDxn%2FQe0TjLhUxJgifKZGONTFXiJo3vSx8s%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MiwibmJmIjoxNzcyOTc4NjUyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.vhgXv3UtQKCYOJpRlpYMGGARRGa2FgYn5HyjSdxiUd0&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-06.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:12--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/87581eb0-de76-4112-9083-604df873c217?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A03%3A58Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-06.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A03%3A51Z&ske=2026-03-08T15%3A03%3A58Z&sks=b&skv=2018-11-09&sig=4xu2vgxN%2BDxn%2FQe0TjLhUxJgifKZGONTFXiJo3vSx8s%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MiwibmJmIjoxNzcyOTc4NjUyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.vhgXv3UtQKCYOJpRlpYMGGARRGa2FgYn5HyjSdxiUd0&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-06.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1154353 (1.1M) [application/octet-stream]
Saving to: ‘data/raw/green/2020/06/green_tripdata_2020_06.csv.gz’

data/raw/green/2020 100%[===================>]   1.10M  --.-KB/s    in 0.03s

2026-03-08 14:04:12 (33.6 MB/s) - ‘data/raw/green/2020/06/green_tripdata_2020_06.csv.gz’ saved [1154353/1154353]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-07.csv.gz to data/raw/green/2020/07/green_tripdata_2020_07.csv.gz
--2026-03-08 14:04:12--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-07.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/f241e232-104f-4fbd-9354-5c4f7a8c7f59?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A44%3A19Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2020-07.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A44%3A15Z&ske=2026-03-08T14%3A44%3A19Z&sks=b&skv=2018-11-09&sig=vixpiVs0nFf7tIVJ1NE2bS7jZBajM28ZvPWFHHgdxTg%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1MiwibmJmIjoxNzcyOTc4NjUyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.vhgXv3UtQKCYOJpRlpYMGGARRGa2FgYn5HyjSdxiUd0&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2020-07.csv.gz&response-content-type=application%2Foctet-stream [following]

In [8]:
!./download_data.sh green 2021

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-01.csv.gz to data/raw/green/2021/01/green_tripdata_2021_01.csv.gz
--2026-03-08 14:04:14--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-01.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/ea387a15-484c-469b-860d-3382ee7659be?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A04%3A27Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-01.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A03%3A54Z&ske=2026-03-08T15%3A04%3A27Z&sks=b&skv=2018-11-09&sig=C%2B8XEpERtCbxHKKOUaH2HnkviG8bBrXs779evxTsYvs%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NCwibmJmIjoxNzcyOTc4NjU0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ._7xGzDthC8489N1PIxtTv-WBUURD9JYGU8FKnafRoRc&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-01.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:14--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/ea387a15-484c-469b-860d-3382ee7659be?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A04%3A27Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-01.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A03%3A54Z&ske=2026-03-08T15%3A04%3A27Z&sks=b&skv=2018-11-09&sig=C%2B8XEpERtCbxHKKOUaH2HnkviG8bBrXs779evxTsYvs%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NCwibmJmIjoxNzcyOTc4NjU0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ._7xGzDthC8489N1PIxtTv-WBUURD9JYGU8FKnafRoRc&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-01.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1403107 (1.3M) [application/octet-stream]
Saving to: ‘data/raw/green/2021/01/green_tripdata_2021_01.csv.gz’

data/raw/green/2021 100%[===================>]   1.34M  --.-KB/s    in 0.03s

2026-03-08 14:04:15 (38.4 MB/s) - ‘data/raw/green/2021/01/green_tripdata_2021_01.csv.gz’ saved [1403107/1403107]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-02.csv.gz to data/raw/green/2021/02/green_tripdata_2021_02.csv.gz
--2026-03-08 14:04:15--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-02.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/34720c37-99b0-4c98-ab5a-4c917f2d0d6f?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A42%3A35Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-02.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A42%3A28Z&ske=2026-03-08T14%3A42%3A35Z&sks=b&skv=2018-11-09&sig=XJkS1mxmi4TPObUKu6Ny5lV6YsD%2FUVaZYa0x2ummsbQ%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NSwibmJmIjoxNzcyOTc4NjU1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.ektmI-Ko8_nExpQ_Zdhc1WP44R7a0q5qR-XAqB8Tg2k&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-02.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:15--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/34720c37-99b0-4c98-ab5a-4c917f2d0d6f?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A42%3A35Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-02.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A42%3A28Z&ske=2026-03-08T14%3A42%3A35Z&sks=b&skv=2018-11-09&sig=XJkS1mxmi4TPObUKu6Ny5lV6YsD%2FUVaZYa0x2ummsbQ%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NSwibmJmIjoxNzcyOTc4NjU1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.ektmI-Ko8_nExpQ_Zdhc1WP44R7a0q5qR-XAqB8Tg2k&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-02.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1176784 (1.1M) [application/octet-stream]
Saving to: ‘data/raw/green/2021/02/green_tripdata_2021_02.csv.gz’

data/raw/green/2021 100%[===================>]   1.12M  --.-KB/s    in 0.03s

2026-03-08 14:04:15 (40.9 MB/s) - ‘data/raw/green/2021/02/green_tripdata_2021_02.csv.gz’ saved [1176784/1176784]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-03.csv.gz to data/raw/green/2021/03/green_tripdata_2021_03.csv.gz
--2026-03-08 14:04:15--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-03.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/b1479513-aea0-4591-b22f-d3f075aee3f8?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A46%3A48Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-03.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A46%3A31Z&ske=2026-03-08T14%3A46%3A48Z&sks=b&skv=2018-11-09&sig=lFzCX2y1qFJjLogghjvJ%2FkCr5xJ7tZSg3zZoEamJ3cs%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NSwibmJmIjoxNzcyOTc4NjU1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.ektmI-Ko8_nExpQ_Zdhc1WP44R7a0q5qR-XAqB8Tg2k&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-03.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:15--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/b1479513-aea0-4591-b22f-d3f075aee3f8?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A46%3A48Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-03.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A46%3A31Z&ske=2026-03-08T14%3A46%3A48Z&sks=b&skv=2018-11-09&sig=lFzCX2y1qFJjLogghjvJ%2FkCr5xJ7tZSg3zZoEamJ3cs%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NSwibmJmIjoxNzcyOTc4NjU1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.ektmI-Ko8_nExpQ_Zdhc1WP44R7a0q5qR-XAqB8Tg2k&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-03.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1522635 (1.5M) [application/octet-stream]
Saving to: ‘data/raw/green/2021/03/green_tripdata_2021_03.csv.gz’

data/raw/green/2021 100%[===================>]   1.45M  --.-KB/s    in 0.03s

2026-03-08 14:04:15 (45.6 MB/s) - ‘data/raw/green/2021/03/green_tripdata_2021_03.csv.gz’ saved [1522635/1522635]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-04.csv.gz to data/raw/green/2021/04/green_tripdata_2021_04.csv.gz
--2026-03-08 14:04:15--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-04.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/63339416-c35e-4c9f-a3cd-98b939d52aca?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A01%3A55Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-04.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A01%3A43Z&ske=2026-03-08T15%3A01%3A55Z&sks=b&skv=2018-11-09&sig=gV6gNSHAg7PrFanCUI1K9yX%2BPNtk7qEb1gdYtMDS6cU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NSwibmJmIjoxNzcyOTc4NjU1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.ektmI-Ko8_nExpQ_Zdhc1WP44R7a0q5qR-XAqB8Tg2k&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-04.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:16--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/63339416-c35e-4c9f-a3cd-98b939d52aca?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A01%3A55Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-04.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A01%3A43Z&ske=2026-03-08T15%3A01%3A55Z&sks=b&skv=2018-11-09&sig=gV6gNSHAg7PrFanCUI1K9yX%2BPNtk7qEb1gdYtMDS6cU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NSwibmJmIjoxNzcyOTc4NjU1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.ektmI-Ko8_nExpQ_Zdhc1WP44R7a0q5qR-XAqB8Tg2k&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-04.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1584480 (1.5M) [application/octet-stream]
Saving to: ‘data/raw/green/2021/04/green_tripdata_2021_04.csv.gz’

data/raw/green/2021 100%[===================>]   1.51M  --.-KB/s    in 0.04s

2026-03-08 14:04:16 (39.9 MB/s) - ‘data/raw/green/2021/04/green_tripdata_2021_04.csv.gz’ saved [1584480/1584480]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-05.csv.gz to data/raw/green/2021/05/green_tripdata_2021_05.csv.gz
--2026-03-08 14:04:16--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-05.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/b46e44d1-5f52-4f06-a7a3-d53dd6b6f85f?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A00%3A57Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-05.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A00%3A44Z&ske=2026-03-08T15%3A00%3A57Z&sks=b&skv=2018-11-09&sig=xs9vukPzL9jPNiF3xE2CHNeKPcDbKKRcN9qFhy7pWqs%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NiwibmJmIjoxNzcyOTc4NjU2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.7eNldevBmbaL3ctQWqFLdd2JYB9P_o7Nl213xcLexzQ&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-05.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:16--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/b46e44d1-5f52-4f06-a7a3-d53dd6b6f85f?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A00%3A57Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-05.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A00%3A44Z&ske=2026-03-08T15%3A00%3A57Z&sks=b&skv=2018-11-09&sig=xs9vukPzL9jPNiF3xE2CHNeKPcDbKKRcN9qFhy7pWqs%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NiwibmJmIjoxNzcyOTc4NjU2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.7eNldevBmbaL3ctQWqFLdd2JYB9P_o7Nl213xcLexzQ&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-05.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1623852 (1.5M) [application/octet-stream]
Saving to: ‘data/raw/green/2021/05/green_tripdata_2021_05.csv.gz’

data/raw/green/2021 100%[===================>]   1.55M  --.-KB/s    in 0.1s

2026-03-08 14:04:16 (11.9 MB/s) - ‘data/raw/green/2021/05/green_tripdata_2021_05.csv.gz’ saved [1623852/1623852]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-06.csv.gz to data/raw/green/2021/06/green_tripdata_2021_06.csv.gz
--2026-03-08 14:04:16--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-06.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5ef384b6-dd62-4601-9e18-e8827e81f782?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A49%3A41Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-06.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A49%3A12Z&ske=2026-03-08T14%3A49%3A41Z&sks=b&skv=2018-11-09&sig=fX8nNhOAtSEX55beciySb8sNbEl5gNzXVCiPYls4U%2BQ%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NiwibmJmIjoxNzcyOTc4NjU2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.7eNldevBmbaL3ctQWqFLdd2JYB9P_o7Nl213xcLexzQ&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-06.csv.gz&response-content-type=application%2Foctet-stream [following]
--2026-03-08 14:04:16--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5ef384b6-dd62-4601-9e18-e8827e81f782?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A49%3A41Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-06.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A49%3A12Z&ske=2026-03-08T14%3A49%3A41Z&sks=b&skv=2018-11-09&sig=fX8nNhOAtSEX55beciySb8sNbEl5gNzXVCiPYls4U%2BQ%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NiwibmJmIjoxNzcyOTc4NjU2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.7eNldevBmbaL3ctQWqFLdd2JYB9P_o7Nl213xcLexzQ&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-06.csv.gz&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1613925 (1.5M) [application/octet-stream]
Saving to: ‘data/raw/green/2021/06/green_tripdata_2021_06.csv.gz’

data/raw/green/2021 100%[===================>]   1.54M  --.-KB/s    in 0.03s

2026-03-08 14:04:16 (49.4 MB/s) - ‘data/raw/green/2021/06/green_tripdata_2021_06.csv.gz’ saved [1613925/1613925]

downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-07.csv.gz to data/raw/green/2021/07/green_tripdata_2021_07.csv.gz
--2026-03-08 14:04:16--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-07.csv.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/a5bb4029-0fe6-4367-b2f6-eb6c8a9d9d86?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T14%3A37%3A59Z&rscd=attachment%3B+filename%3Dgreen_tripdata_2021-07.csv.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T13%3A37%3A34Z&ske=2026-03-08T14%3A37%3A59Z&sks=b&skv=2018-11-09&sig=WNBbLCDKolY%2BBGqEH%2FcZa1%2BkB3wALViiUyur1THcQpc%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk3ODk1NywibmJmIjoxNzcyOTc4NjU3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.uDjSSuKMGrsE_0fuiqBfc70HcSecFEcImCl9AT2EbGQ&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2021-07.csv.gz&response-content-type=application%2Foctet-stream [following]

In [9]:
!sudo apt-get install tree

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  tree
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 47.9 kB of archives.
After this operation, 116 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tree amd64 2.0.2-1 [47.9 kB]
Fetched 47.9 kB in 0s (163 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package tree.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../tree_2.0.2-1_amd64.deb ...
Unpacking tree (2.0.2-1) ...
Setting up tree (2.0.2-1) ...
Processing triggers for man-db (2.10.2-1) ...

In [10]:
!tree data

data
└── raw
    ├── green
    │   ├── 2020
    │   │   ├── 01
    │   │   │   └── green_tripdata_2020_01.csv.gz
    │   │   ├── 02
    │   │   │   └── green_tripdata_2020_02.csv.gz
    │   │   ├── 03
    │   │   │   └── green_tripdata_2020_03.csv.gz
    │   │   ├── 04
    │   │   │   └── green_tripdata_2020_04.csv.gz
    │   │   ├── 05
    │   │   │   └── green_tripdata_2020_05.csv.gz
    │   │   ├── 06
    │   │   │   └── green_tripdata_2020_06.csv.gz
    │   │   ├── 07
    │   │   │   └── green_tripdata_2020_07.csv.gz
    │   │   ├── 08
    │   │   │   └── green_tripdata_2020_08.csv.gz
    │   │   ├── 09
    │   │   │   └── green_tripdata_2020_09.csv.gz
    │   │   ├── 10
    │   │   │   └── green_tripdata_2020_10.csv.gz
    │   │   ├── 11
    │   │   │   └── green_tripdata_2020_11.csv.gz
    │   │   └── 12
    │   │       └── green_tripdata_2020_12.csv.gz
    │   └── 2021
    │       ├── 01
    │       │   └── green_tripdata_2021_01.csv.gz
    │       ├── 02
    │       │   └── green_tripdata_2021_02.csv.gz
    │       ├── 03
    │       │   └── green_tripdata_2021_03.csv.gz
    │       ├── 04
    │       │   └── green_tripdata_2021_04.csv.gz
    │       ├── 05
    │       │   └── green_tripdata_2021_05.csv.gz
    │       ├── 06
    │       │   └── green_tripdata_2021_06.csv.gz
    │       ├── 07
    │       │   └── green_tripdata_2021_07.csv.gz
    │       └── 08
    │           └── green_tripdata_2021_08.csv.gz
    └── yellow
        ├── 2020
        │   ├── 01
        │   │   └── yellow_tripdata_2020_01.csv.gz
        │   ├── 02
        │   │   └── yellow_tripdata_2020_02.csv.gz
        │   ├── 03
        │   │   └── yellow_tripdata_2020_03.csv.gz
        │   ├── 04
        │   │   └── yellow_tripdata_2020_04.csv.gz
        │   ├── 05
        │   │   └── yellow_tripdata_2020_05.csv.gz
        │   ├── 06
        │   │   └── yellow_tripdata_2020_06.csv.gz
        │   ├── 07
        │   │   └── yellow_tripdata_2020_07.csv.gz
        │   ├── 08
        │   │   └── yellow_tripdata_2020_08.csv.gz
        │   ├── 09
        │   │   └── yellow_tripdata_2020_09.csv.gz
        │   ├── 10
        │   │   └── yellow_tripdata_2020_10.csv.gz
        │   ├── 11
        │   │   └── yellow_tripdata_2020_11.csv.gz
        │   └── 12
        │       └── yellow_tripdata_2020_12.csv.gz
        └── 2021
            ├── 01
            │   └── yellow_tripdata_2021_01.csv.gz
            ├── 02
            │   └── yellow_tripdata_2021_02.csv.gz
            ├── 03
            │   └── yellow_tripdata_2021_03.csv.gz
            ├── 04
            │   └── yellow_tripdata_2021_04.csv.gz
            ├── 05
            │   └── yellow_tripdata_2021_05.csv.gz
            ├── 06
            │   └── yellow_tripdata_2021_06.csv.gz
            ├── 07
            │   └── yellow_tripdata_2021_07.csv.gz
            └── 08
                └── yellow_tripdata_2021_08.csv.gz

47 directories, 40 files

## Defining Schema

In [11]:
import pyspark
from pyspark.sql import SparkSession

In [12]:
# Initialize spark session
spark = SparkSession.builder \
    .appName('spark_session_02') \
    .getOrCreate()

In [13]:
from pyspark.sql import types

In [14]:
green_schema = types.StructType ([
    types.StructField('VendorID', types.IntegerType(), True),
    types.StructField('lpep_pickup_datetime', types.TimestampType(), True),
    types.StructField('lpep_dropoff_datetime', types.TimestampType(), True),
    types.StructField('store_and_fwd_flag', types.StringType(), True),
    types.StructField('RatecodeID', types.IntegerType(), True),
    types.StructField('PULocationID', types.IntegerType(), True),
    types.StructField('DOLocationID', types.IntegerType(), True),
    types.StructField('passenger_count', types.IntegerType(), True),
    types.StructField('trip_distance', types.DoubleType(), True),
    types.StructField('fare_amount', types.DoubleType(), True),
    types.StructField('extra', types.DoubleType(), True),
    types.StructField('mta_tax', types.DoubleType(), True),
    types.StructField('tip_amount', types.DoubleType(), True),
    types.StructField('tolls_amount', types.DoubleType(), True),
    types.StructField('ehail_fee', types.DoubleType(), True),
    types.StructField('improvement_surcharge', types.DoubleType(), True),
    types.StructField('total_amount', types.DoubleType(), True),
    types.StructField('payment_type', types.IntegerType(), True),
    types.StructField('trip_type', types.IntegerType(), True),
    types.StructField('congestion_surcharge', types.DoubleType(), True)
])

In [15]:
year = 2020

for month in range(1, 13):
  print(f'Data is being processed: {year}/{month}')
  input_path = f"data/raw/green/{year}/{month:02d}/"
  output_path = f"data/parquet/green/{year}/{month:02d}/"

df_green = spark.read \
    .option("header", "true") \
    .schema(green_schema) \
    .csv(input_path)

df_green \
        .repartition(4)\
        .write.parquet(output_path)

Data is being processed: 2020/1
Data is being processed: 2020/2
Data is being processed: 2020/3
Data is being processed: 2020/4
Data is being processed: 2020/5
Data is being processed: 2020/6
Data is being processed: 2020/7
Data is being processed: 2020/8
Data is being processed: 2020/9
Data is being processed: 2020/10
Data is being processed: 2020/11
Data is being processed: 2020/12

In [16]:
df_green.printSchema()

root
 |-- VendorID: integer (nullable = true)
 |-- lpep_pickup_datetime: timestamp (nullable = true)
 |-- lpep_dropoff_datetime: timestamp (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- RatecodeID: integer (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- passenger_count: integer (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- ehail_fee: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- payment_type: integer (nullable = true)
 |-- trip_type: integer (nullable = true)
 |-- congestion_surcharge: double (nullable = true)

In [17]:
import pandas as pd

In [18]:
df_green_pd = pd.read_csv('data/raw/green/2021/01/green_tripdata_2021_01.csv.gz', nrows=1000)

In [19]:
df_green_pd

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2021-01-01 00:15:56,2021-01-01 00:19:52,N,1,43,151,1,1.01,5.5,0.5,0.5,0.00,0.00,NaN,0.3,6.80,2,1,0.00
1,2,2021-01-01 00:25:59,2021-01-01 00:34:44,N,1,166,239,1,2.53,10.0,0.5,0.5,2.81,0.00,NaN,0.3,16.86,1,1,2.75
2,2,2021-01-01 00:45:57,2021-01-01 00:51:55,N,1,41,42,1,1.12,6.0,0.5,0.5,1.00,0.00,NaN,0.3,8.30,1,1,0.00
3,2,2020-12-31 23:57:51,2021-01-01 00:04:56,N,1,168,75,1,1.99,8.0,0.5,0.5,0.00,0.00,NaN,0.3,9.30,2,1,0.00
4,2,2021-01-01 00:16:36,2021-01-01 00:16:40,N,2,265,265,3,0.00,-52.0,0.0,-0.5,0.00,0.00,NaN,-0.3,-52.80,3,1,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2,2021-01-02 12:48:43,2021-01-02 13:54:15,N,1,15,177,1,25.76,77.0,0.0,0.5,2.75,12.24,NaN,0.3,92.79,1,1,0.00
996,1,2021-01-02 12:16:47,2021-01-02 12:24:56,N,1,116,74,1,2.00,9.0,0.0,0.5,1.95,0.00,NaN,0.3,11.75,1,1,0.00
997,2,2021-01-02 12:07:17,2021-01-02 12:12:06,N,1,42,41,1,0.87,5.5,0.0,0.5,0.00,0.00,NaN,0.3,6.30,2,1,0.00
998,2,2021-01-02 12:32:45,2021-01-02 12:59:46,N,1,82,218,1,11.88,35.0,0.0,0.5,0.00,0.00,NaN,0.3,35.80,2,1,0.00
999,2,2021-01-02 12:02:46,2021-01-02 12:09:02,N,1,166,116,1,0.90,6.0,0.0,0.5,0.00,0.00,NaN,0.3,6.80,2,1,0.00

In [20]:
# Adjust file types
spark.createDataFrame(df_green_pd).schema

StructType([StructField('VendorID', LongType(), True), StructField('lpep_pickup_datetime', StringType(), True), StructField('lpep_dropoff_datetime', StringType(), True), StructField('store_and_fwd_flag', StringType(), True), StructField('RatecodeID', LongType(), True), StructField('PULocationID', LongType(), True), StructField('DOLocationID', LongType(), True), StructField('passenger_count', LongType(), True), StructField('trip_distance', DoubleType(), True), StructField('fare_amount', DoubleType(), True), StructField('extra', DoubleType(), True), StructField('mta_tax', DoubleType(), True), StructField('tip_amount', DoubleType(), True), StructField('tolls_amount', DoubleType(), True), StructField('ehail_fee', DoubleType(), True), StructField('improvement_surcharge', DoubleType(), True), StructField('total_amount', DoubleType(), True), StructField('payment_type', LongType(), True), StructField('trip_type', LongType(), True), StructField('congestion_surcharge', DoubleType(), True)])

## Yellow Data Schema

In [21]:
df_yellow_pd = pd.read_csv("data/raw/yellow/2021/01/yellow_tripdata_2021_01.csv.gz", nrows=1000)

In [22]:
spark.createDataFrame(df_yellow_pd).schema

StructType([StructField('VendorID', LongType(), True), StructField('tpep_pickup_datetime', StringType(), True), StructField('tpep_dropoff_datetime', StringType(), True), StructField('passenger_count', LongType(), True), StructField('trip_distance', DoubleType(), True), StructField('RatecodeID', LongType(), True), StructField('store_and_fwd_flag', StringType(), True), StructField('PULocationID', LongType(), True), StructField('DOLocationID', LongType(), True), StructField('payment_type', LongType(), True), StructField('fare_amount', DoubleType(), True), StructField('extra', DoubleType(), True), StructField('mta_tax', DoubleType(), True), StructField('tip_amount', DoubleType(), True), StructField('tolls_amount', DoubleType(), True), StructField('improvement_surcharge', DoubleType(), True), StructField('total_amount', DoubleType(), True), StructField('congestion_surcharge', DoubleType(), True)])

In [23]:
yellow_schema = types.StructType ([
      types.StructField('VendorID', types.IntegerType(), True),
      types.StructField('tpep_pickup_datetime', types.TimestampType(), True),
      types.StructField('tpep_dropoff_datetime', types.TimestampType(), True),
      types.StructField('passenger_count', types.IntegerType(), True),
      types.StructField('trip_distance', types.DoubleType(), True),
      types.StructField('RatecodeID', types.IntegerType(), True),
      types.StructField('store_and_fwd_flag', types.StringType(), True),
      types.StructField('PULocationID', types.IntegerType(), True),
      types.StructField('DOLocationID', types.IntegerType(), True),
      types.StructField('payment_type', types.IntegerType(), True),
      types.StructField('fare_amount', types.DoubleType(), True),
      types.StructField('extra', types.DoubleType(), True),
      types.StructField('mta_tax', types.DoubleType(), True),
      types.StructField('tip_amount', types.DoubleType(), True),
      types.StructField('tolls_amount', types.DoubleType(), True),
      types.StructField('improvement_surcharge', types.DoubleType(), True),
      types.StructField('total_amount', types.DoubleType(), True),
      types.StructField('congestion_surcharge', types.DoubleType(), True)
      ])

In [24]:
df_yellow = spark.read \
            .option("header", "true") \
            .schema(yellow_schema) \
            .csv("data/raw/yellow/2021/01/")

In [25]:
year = 2020

for month in range(1, 13):
  print(f'Data is being processed: {year}/{month}')
  input_path = f"data/raw/yellow/{year}/{month:02d}/"
  output_path = f"data/parquet/yellow/{year}/{month:02d}/"

df_yellow = spark.read \
    .option("header", "true") \
    .schema(yellow_schema) \
    .csv(input_path)

df_yellow \
        .repartition(4)\
        .write.parquet(output_path)

Data is being processed: 2020/1
Data is being processed: 2020/2
Data is being processed: 2020/3
Data is being processed: 2020/4
Data is being processed: 2020/5
Data is being processed: 2020/6
Data is being processed: 2020/7
Data is being processed: 2020/8
Data is being processed: 2020/9
Data is being processed: 2020/10
Data is being processed: 2020/11
Data is being processed: 2020/12

In [26]:
!tree data

data
├── parquet
│   ├── green
│   │   └── 2020
│   │       └── 12
│   │           ├── part-00000-737b42e2-a328-4b94-9041-372bb1cf0330-c000.snappy.parquet
│   │           ├── part-00001-737b42e2-a328-4b94-9041-372bb1cf0330-c000.snappy.parquet
│   │           ├── part-00002-737b42e2-a328-4b94-9041-372bb1cf0330-c000.snappy.parquet
│   │           ├── part-00003-737b42e2-a328-4b94-9041-372bb1cf0330-c000.snappy.parquet
│   │           └── _SUCCESS
│   └── yellow
│       └── 2020
│           └── 12
│               ├── part-00000-170eeb02-93ea-4652-a0f5-be88a3a6eacc-c000.snappy.parquet
│               ├── part-00001-170eeb02-93ea-4652-a0f5-be88a3a6eacc-c000.snappy.parquet
│               ├── part-00002-170eeb02-93ea-4652-a0f5-be88a3a6eacc-c000.snappy.parquet
│               ├── part-00003-170eeb02-93ea-4652-a0f5-be88a3a6eacc-c000.snappy.parquet
│               └── _SUCCESS
└── raw
    ├── green
    │   ├── 2020
    │   │   ├── 01
    │   │   │   └── green_tripdata_2020_01.csv.gz
    │   │   ├── 02
    │   │   │   └── green_tripdata_2020_02.csv.gz
    │   │   ├── 03
    │   │   │   └── green_tripdata_2020_03.csv.gz
    │   │   ├── 04
    │   │   │   └── green_tripdata_2020_04.csv.gz
    │   │   ├── 05
    │   │   │   └── green_tripdata_2020_05.csv.gz
    │   │   ├── 06
    │   │   │   └── green_tripdata_2020_06.csv.gz
    │   │   ├── 07
    │   │   │   └── green_tripdata_2020_07.csv.gz
    │   │   ├── 08
    │   │   │   └── green_tripdata_2020_08.csv.gz
    │   │   ├── 09
    │   │   │   └── green_tripdata_2020_09.csv.gz
    │   │   ├── 10
    │   │   │   └── green_tripdata_2020_10.csv.gz
    │   │   ├── 11
    │   │   │   └── green_tripdata_2020_11.csv.gz
    │   │   └── 12
    │   │       └── green_tripdata_2020_12.csv.gz
    │   └── 2021
    │       ├── 01
    │       │   └── green_tripdata_2021_01.csv.gz
    │       ├── 02
    │       │   └── green_tripdata_2021_02.csv.gz
    │       ├── 03
    │       │   └── green_tripdata_2021_03.csv.gz
    │       ├── 04
    │       │   └── green_tripdata_2021_04.csv.gz
    │       ├── 05
    │       │   └── green_tripdata_2021_05.csv.gz
    │       ├── 06
    │       │   └── green_tripdata_2021_06.csv.gz
    │       ├── 07
    │       │   └── green_tripdata_2021_07.csv.gz
    │       └── 08
    │           └── green_tripdata_2021_08.csv.gz
    └── yellow
        ├── 2020
        │   ├── 01
        │   │   └── yellow_tripdata_2020_01.csv.gz
        │   ├── 02
        │   │   └── yellow_tripdata_2020_02.csv.gz
        │   ├── 03
        │   │   └── yellow_tripdata_2020_03.csv.gz
        │   ├── 04
        │   │   └── yellow_tripdata_2020_04.csv.gz
        │   ├── 05
        │   │   └── yellow_tripdata_2020_05.csv.gz
        │   ├── 06
        │   │   └── yellow_tripdata_2020_06.csv.gz
        │   ├── 07
        │   │   └── yellow_tripdata_2020_07.csv.gz
        │   ├── 08
        │   │   └── yellow_tripdata_2020_08.csv.gz
        │   ├── 09
        │   │   └── yellow_tripdata_2020_09.csv.gz
        │   ├── 10
        │   │   └── yellow_tripdata_2020_10.csv.gz
        │   ├── 11
        │   │   └── yellow_tripdata_2020_11.csv.gz
        │   └── 12
        │       └── yellow_tripdata_2020_12.csv.gz
        └── 2021
            ├── 01
            │   └── yellow_tripdata_2021_01.csv.gz
            ├── 02
            │   └── yellow_tripdata_2021_02.csv.gz
            ├── 03
            │   └── yellow_tripdata_2021_03.csv.gz
            ├── 04
            │   └── yellow_tripdata_2021_04.csv.gz
            ├── 05
            │   └── yellow_tripdata_2021_05.csv.gz
            ├── 06
            │   └── yellow_tripdata_2021_06.csv.gz
            ├── 07
            │   └── yellow_tripdata_2021_07.csv.gz
            └── 08
                └── yellow_tripdata_2021_08.csv.gz

54 directories, 50 files

# SQL with Spark

In [27]:
# Read green parquet files
df_green_parquet = spark.read.parquet('data/parquet/green/*/*')

In [28]:
# rename dropoff and pickup time

df_green_parquet = df_green_parquet \
              .withColumnRenamed('lpep_pickup_datetime', 'pickup_datetime') \
              .withColumnRenamed('lpep_dropoff_datetime', 'dropoff_datetime')

In [29]:
df_green_parquet.show()

+--------+-------------------+-------------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------+---------------------+------------+------------+---------+--------------------+
|VendorID|    pickup_datetime|   dropoff_datetime|store_and_fwd_flag|RatecodeID|PULocationID|DOLocationID|passenger_count|trip_distance|fare_amount|extra|mta_tax|tip_amount|tolls_amount|ehail_fee|improvement_surcharge|total_amount|payment_type|trip_type|congestion_surcharge|
+--------+-------------------+-------------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------+---------------------+------------+------------+---------+--------------------+
|       2|2020-12-22 16:05:01|2020-12-22 18:34:59|                 N|         1|         189|         163|              5|         3.73|       24.0|  1.0|    0.5|      5.16|         0.0|     NULL|                  0.3|       30.96|           1|        1|                 0.0|
|    NULL|2020-12-01 15:35:00|2020-12-01 16:02:00|              NULL|      NULL|          82|          98|           NULL|         7.44|      25.36|  0.0|    0.0|      2.75|         0.0|     NULL|                  0.3|       28.41|        NULL|     NULL|                NULL|
|    NULL|2020-12-23 21:14:00|2020-12-23 21:35:00|              NULL|      NULL|          61|         255|           NULL|          3.8|      25.95|  0.0|    0.0|      2.75|         0.0|     NULL|                  0.3|        29.0|        NULL|     NULL|                NULL|
|    NULL|2020-12-15 14:26:00|2020-12-15 15:27:00|              NULL|      NULL|         231|         155|           NULL|        10.35|      37.33|  0.0|    0.0|      2.75|        6.12|     NULL|                  0.3|        46.5|        NULL|     NULL|                NULL|
|       2|2020-12-18 13:26:08|2020-12-18 13:48:10|                 N|         1|          75|         151|              1|         1.56|       14.0|  0.0|    0.5|       2.0|         0.0|     NULL|                  0.3|        16.8|           1|        1|                 0.0|
|       2|2020-12-04 18:00:56|2020-12-04 18:10:55|                 N|         1|          75|         263|              6|         1.13|        8.0|  1.0|    0.5|      2.51|         0.0|     NULL|                  0.3|       15.06|           1|        1|                2.75|
|    NULL|2020-12-01 06:57:00|2020-12-01 07:19:00|              NULL|      NULL|         159|         242|           NULL|         8.62|      27.27|  0.0|    0.0|      2.75|         0.0|     NULL|                  0.3|       30.32|        NULL|     NULL|                NULL|
|       2|2020-12-04 15:01:16|2020-12-04 15:10:18|                 N|         1|         130|         191|              1|         2.31|        9.5|  0.0|    0.5|       0.0|         0.0|     NULL|                  0.3|        10.3|           2|        1|                 0.0|
|       1|2020-12-28 15:09:34|2020-12-28 15:14:30|                 N|         1|          42|          42|              1|          0.9|        5.5|  0.0|    0.5|       0.0|         0.0|     NULL|                  0.3|         6.3|           2|        1|                 0.0|
|       2|2020-12-07 10:14:19|2020-12-07 10:22:53|                 N|         1|          42|         262|              1|         3.51|       11.5|  0.0|    0.5|       2.0|         0.0|     NULL|                  0.3|       17.05|           1|        1|                2.75|
|       2|2020-12-27 17:39:57|2020-12-27 17:46:31|                 N|         1|          41|          74|              1|         0.81|        6.0|  0.0|    0.5|       0.0|         0.0|     NULL|                  0.3|         6.8|           2|        1|                 0.0|
|    NULL|2020-12-03 13:21:00|2020-12-03 13:56:00|              NULL|      NULL|         119|         234|           NULL|        11.13|      32.54|  0.0|    0.0|      2.75|         0.0|     NULL|                  0.3|       35.59|        NULL|     NULL|                NULL|
|    NULL|2020-12-01 14:57:00|2020-12-01 15:23:00|              NULL|      NULL|         197|           9|           NULL|         6.97|      32.95|  0.0|    0.0|      2.75|         0.0|     NULL|                  0.3|        36.0|        NULL|     NULL|                NULL|
|    NULL|2020-12-22 20:50:00|2020-12-22 20:56:00|              NULL|      NULL|          35|          61|           NULL|         0.69|      16.73|  0.0|    0.0|      2.75|         0.0|     NULL|                  0.3|       19.78|        NULL|     NULL|                NULL|
|       2|2020-12-23 16:10:42|2020-12-23 17:10:24|                 N|         1|         197|          49|              1|        13.22|       47.5|  1.0|    0.5|      2.75|         0.0|     NULL|                  0.3|       52.05|           1|        1|                 0.0|
|    NULL|2020-12-02 00:05:00|2020-12-02 00:19:00|              NULL|      NULL|         168|         235|           NULL|         2.79|      18.52|  0.0|    0.0|      2.75|         0.0|     NULL|                  0.3|       21.57|        NULL|     NULL|                NULL|
|       2|2020-12-07 08:29:48|2020-12-07 08:37:21|                 N|         1|          74|          75|              5|         1.23|        6.5|  0.0|    0.5|       0.0|         0.0|     NULL|                  0.3|         7.3|           2|        1|                 0.0|
|    NULL|2020-12-29 17:33:00|2020-12-29 17:39:00|              NULL|      NULL|         169|         235|           NULL|         0.51|      12.62|  0.0|    0.0|      2.75|         0.0|     NULL|                  0.3|       15.67|        NULL|     NULL|                NULL|
|       2|2020-12-01 08:34:57|2020-12-01 08:56:32|                 N|         1|          74|         141|              1|         2.75|       15.0|  0.0|    0.5|      3.71|         0.0|     NULL|                  0.3|       22.26|           1|        1|                2.75|
|    NULL|2020-12-24 09:48:00|2020-12-24 10:18:00|              NULL|      NULL|          51|         140|           NULL|        13.21|       34.2|  0.0|    0.0|      2.75|       12.24|     NULL|                  0.3|       49.49|        NULL|     NULL|                NULL|
+--------+-------------------+-------------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------+---------------------+------------+------------+---------+--------------------+
only showing top 20 rows

In [30]:
df_yellow_parquet = spark.read.parquet('data/parquet/yellow/*/*')

In [31]:
df_yellow_parquet = df_yellow_parquet \
                  .withColumnRenamed('tpep_pickup_datetime', 'pickup_datetime') \
                  .withColumnRenamed('tpep_dropoff_datetime', 'dropoff_datetime')

In [32]:
common_columns = []

yellow_columns = set(df_yellow_parquet.columns)

for col in df_green_parquet.columns:
  if col in df_yellow_parquet.columns:
    common_columns.append(col)

In [33]:
df_yellow_parquet

DataFrame[VendorID: int, pickup_datetime: timestamp, dropoff_datetime: timestamp, passenger_count: int, trip_distance: double, RatecodeID: int, store_and_fwd_flag: string, PULocationID: int, DOLocationID: int, payment_type: int, fare_amount: double, extra: double, mta_tax: double, tip_amount: double, tolls_amount: double, improvement_surcharge: double, total_amount: double, congestion_surcharge: double]

In [34]:
common_columns

['VendorID',
 'pickup_datetime',
 'dropoff_datetime',
 'store_and_fwd_flag',
 'RatecodeID',
 'PULocationID',
 'DOLocationID',
 'passenger_count',
 'trip_distance',
 'fare_amount',
 'extra',
 'mta_tax',
 'tip_amount',
 'tolls_amount',
 'improvement_surcharge',
 'total_amount',
 'payment_type',
 'congestion_surcharge']

In [35]:
from pyspark.sql import functions as F

In [36]:
df_green_service = df_green_parquet\
                .select(common_columns) \
                .withColumn('service_type', F.lit('green'))

In [37]:
df_yellow_service = df_yellow_parquet\
                .select(common_columns) \
                .withColumn('service_type', F.lit('yellow'))

In [38]:
df_trips_data = df_green_service.unionAll(df_yellow_service)

In [39]:
df_trips_data.groupBy('service_type').count().show()

+------------+-------+
|service_type|  count|
+------------+-------+
|       green|  83130|
|      yellow|1461897|
+------------+-------+

## Querying the Data

In [40]:
df_trips_data.registerTempTable("trips_data")

/usr/local/lib/python3.12/dist-packages/pyspark/sql/classic/dataframe.py:178: FutureWarning: Deprecated in 2.0, use createOrReplaceTempView instead.
  warnings.warn("Deprecated in 2.0, use createOrReplaceTempView instead.", FutureWarning)

In [41]:
spark.sql(
  """
    SELECT
      service_type,
      count(1)
    FROM
      trips_data
    GROUP BY service_type
  """
).show()

+------------+--------+
|service_type|count(1)|
+------------+--------+
|       green|   83130|
|      yellow| 1461897|
+------------+--------+

In [42]:
df_nyc_taxi = spark.sql (
    """
      SELECT
      -- Revenue grouping
      PULocationID AS revenue_zone,
      date_trunc('month', pickup_datetime) AS revenue_month,
      service_type,

      -- Revenue calculation
      SUM(fare_amount) AS revenue_monthly_fare,
      SUM(extra) AS revenue_monthly_extra,
      SUM(mta_tax) AS revenue_monthly_mta_tax,
      SUM(tip_amount) AS revenue_monthly_tip_amount,
      SUM(tolls_amount) AS revenue_monthly_tolls_amount,
      SUM(improvement_surcharge) AS revenue_monthly_improvement_surcharge,
      SUM(total_amount) AS revenue_monthly_total_amount,
      SUM(congestion_surcharge) AS revenue_monthly_congestion_surcharge,

      -- Additional calculations
      AVG(passenger_count) AS avg_monthly_passenger_count,
      AVG(trip_distance) AS avg_monthly_trip_distance
  FROM
      trips_data
  GROUP BY
      1, 2, 3
  """)

In [43]:
df_nyc_taxi.show()

+------------+-------------------+------------+--------------------+---------------------+-----------------------+--------------------------+----------------------------+-------------------------------------+----------------------------+------------------------------------+---------------------------+-------------------------+
|revenue_zone|      revenue_month|service_type|revenue_monthly_fare|revenue_monthly_extra|revenue_monthly_mta_tax|revenue_monthly_tip_amount|revenue_monthly_tolls_amount|revenue_monthly_improvement_surcharge|revenue_monthly_total_amount|revenue_monthly_congestion_surcharge|avg_monthly_passenger_count|avg_monthly_trip_distance|
+------------+-------------------+------------+--------------------+---------------------+-----------------------+--------------------------+----------------------------+-------------------------------------+----------------------------+------------------------------------+---------------------------+-------------------------+
|         131|2020-12-01 00:00:00|       green|   5490.599999999999|                  0.0|                    1.5|                    561.14|                      128.03|                     58.5000000000001|           6242.519999999997|                                 0.0|                        1.0|         5.94010152284264|
|          15|2020-12-01 00:00:00|       green|              709.52|                  0.0|                    0.0|                     63.25|                       12.24|                    6.899999999999999|           791.9100000000001|                                NULL|                       NULL|        6.340434782608695|
|          51|2020-12-01 00:00:00|       green|             15897.0|                  6.5|                   15.0|                   1553.16|          1073.2000000000005|                   173.99999999999906|          18718.860000000037|                                 0.0|          1.027027027027027|        6.617560137457047|
|          72|2020-12-01 00:00:00|       green|   12406.25999999998|                 10.5|                   14.0|        1284.6100000000001|           335.0600000000001|                   142.49999999999937|          14195.679999999997|                                 0.0|         1.1428571428571428|        5.623305263157896|
|          41|2020-12-01 00:00:00|       green|   50194.93000000005|              1350.75|                 2086.0|                   5555.07|           540.8500000000003|                   1385.9999999999725|          63509.549999998504|                              2629.0|         1.2007083825265643|       2.2153635972461276|
|          73|2020-12-01 00:00:00|       green|              417.74|                  0.0|                    0.5|                      30.8|                       18.36|                    4.199999999999999|                       471.6|                                 0.0|                        1.0|        6.785000000000001|
|          50|2020-12-01 00:00:00|       green|              601.77|                  0.0|                    0.0|                     52.25|                       12.24|                    5.699999999999999|                      671.96|                                NULL|                       NULL|        8.829999999999998|
|          52|2020-12-01 00:00:00|       green|   8438.399999999998|                201.0|                  295.0|        1260.0300000000002|                        30.6|                   194.99999999999886|          10624.530000000039|                              200.75|         1.3444816053511706|        2.850454545454545|
|          56|2020-12-01 00:00:00|       green|   6279.549999999997|                 13.5|                   24.0|         607.8999999999999|          250.92000000000007|                                 75.3|           7256.670000000004|                                 0.0|         1.1886792452830188|        5.276877470355732|
|         125|2020-12-01 00:00:00|       green|               68.61|                  0.0|                    0.0|                       5.5|                         0.0|                                  0.6|           74.71000000000001|                                NULL|                       NULL|                    16.04|
|         147|2020-12-01 00:00:00|       green|   3399.119999999999|                  6.0|                   13.0|                    288.28|          210.88000000000005|                    37.50000000000004|          3957.5299999999997|                                2.75|          1.131578947368421|        6.199925373134328|
|         180|2020-12-01 00:00:00|       green|              749.63|                  0.0|                    0.5|                     57.75|                       36.72|                                  6.6|           851.1999999999998|                                 0.0|                        1.0|        9.284090909090908|
|         143|2020-12-01 00:00:00|       green|               502.0|                  0.0|                    0.0|                      44.0|                       18.36|                                  4.8|           569.1600000000001|                                NULL|                       NULL|                    8.695|
|          78|2020-12-01 00:00:00|       green|   7730.379999999999|                 12.0|                   28.5|                    771.69|           442.9300000000002|                    92.69999999999983|           9089.200000000006|                                 5.5|         1.1126760563380282|        355.5357827476038|
|         182|2020-12-01 00:00:00|       green|   8247.830000000007|                 14.0|                   17.5|                    787.87|           470.7900000000002|                    93.29999999999983|           9631.290000000006|                                 0.0|         1.0377358490566038|           6.058173374613|
|         262|2020-12-01 00:00:00|       green|              674.38|                  0.0|                    1.5|                     57.45|                       42.84|                    6.299999999999999|                      782.47|                                 0.0|         2.3333333333333335|        8.446190476190477|
|         178|2020-12-01 00:00:00|       green|   914.7999999999997|                  0.0|                    0.5|                    123.75|                       12.24|                   13.799999999999995|                     1065.09|                                 0.0|                        1.0|       3.3539583333333334|
|         227|2020-12-01 00:00:00|       green|  7972.2199999999975|                  6.0|                   34.0|         618.6800000000001|                       96.38|                    69.60000000000005|           8799.630000000005|                                 0.0|         1.0285714285714285|       10.302629310344829|
|         202|2020-12-01 00:00:00|       green|              646.54|                  0.5|                    2.0|                     56.56|                       12.24|                    6.599999999999999|                      727.19|                                2.75|                        1.0|        7.323181818181819|
|         220|2020-12-01 00:00:00|       green|   6635.369999999997|                 12.0|                   16.0|         649.5899999999999|          182.82999999999998|                                 75.6|           7579.640000000002|                                 5.5|                      1.025|         5.41295275590551|
+------------+-------------------+------------+--------------------+---------------------+-----------------------+--------------------------+----------------------------+-------------------------------------+----------------------------+------------------------------------+---------------------------+-------------------------+
only showing top 20 rows

In [44]:
# Save results in parquet

df_nyc_taxi.coalesce(1).write.parquet("data/report/revenue/", mode="overwrite")

# GroupBy & Joins

In [56]:
!pip install pyngrok

Collecting pyngrok
  Downloading pyngrok-7.5.1-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Downloading pyngrok-7.5.1-py3-none-any.whl (24 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-7.5.1

In [57]:

# Acess SparkUI with Ngrok endpoint
from pyngrok import ngrok, conf
import getpass

conf.get_default().auth_token = getpass.getpass()

ui_port = 4040
public_url = ngrok.connect(ui_port).public_url
print(f" * ngrok tunnel \"{public_url}\" -> \"http://127.0.0.1:{ui_port}\"")

··········

WARNING:pyngrok.process.ngrok:t=2026-03-08T14:17:50+0000 lvl=warn msg="can't bind default web address, trying alternatives" obj=web addr=127.0.0.1:4040

 * ngrok tunnel "https://senaida-interlobular-franklyn.ngrok-free.dev" -> "http://127.0.0.1:4040"

In [45]:
df_green.registerTempTable("green")

/usr/local/lib/python3.12/dist-packages/pyspark/sql/classic/dataframe.py:178: FutureWarning: Deprecated in 2.0, use createOrReplaceTempView instead.
  warnings.warn("Deprecated in 2.0, use createOrReplaceTempView instead.", FutureWarning)

In [54]:
df_green_result = spark.sql (
    """
      SELECT
      PULocationID AS zone,
      date_trunc('hour', lpep_pickup_datetime) AS pickup_hour,
      SUM(total_amount) AS revenue_monthly_total_amount,
      COUNT(1) AS number_records
  FROM
      green
  WHERE lpep_pickup_datetime >= '2020-01-01 00:00:00'
  GROUP BY
      1, 2
  ORDER BY
      1, 2
  """)

In [59]:
df_green_result.show()

+----+-------------------+----------------------------+--------------+
|zone|        pickup_hour|revenue_monthly_total_amount|number_records|
+----+-------------------+----------------------------+--------------+
|   1|2020-12-30 15:00:00|                      120.39|             1|
|   3|2020-12-01 07:00:00|                       30.32|             1|
|   3|2020-12-01 09:00:00|                       45.86|             2|
|   3|2020-12-01 10:00:00|                       16.67|             1|
|   3|2020-12-01 15:00:00|                        12.0|             1|
|   3|2020-12-02 05:00:00|                       62.87|             1|
|   3|2020-12-02 09:00:00|                       88.81|             3|
|   3|2020-12-02 10:00:00|                       78.17|             3|
|   3|2020-12-02 11:00:00|                       22.01|             1|
|   3|2020-12-02 13:00:00|                       22.01|             1|
|   3|2020-12-02 17:00:00|                       25.84|             1|
|   3|2020-12-03 09:00:00|                       50.21|             1|
|   3|2020-12-03 10:00:00|                       33.34|             2|
|   3|2020-12-03 11:00:00|           83.57000000000001|             3|
|   3|2020-12-03 12:00:00|                       16.67|             1|
|   3|2020-12-03 13:00:00|                       30.32|             1|
|   3|2020-12-03 15:00:00|                       45.24|             1|
|   3|2020-12-03 19:00:00|                       74.81|             1|
|   3|2020-12-03 20:00:00|                       23.85|             1|
|   3|2020-12-04 06:00:00|                       41.29|             1|
+----+-------------------+----------------------------+--------------+
only showing top 20 rows

In [60]:
df_green_result.write.parquet('data/report/revenue/green', mode='overwrite')

In [62]:
df_yellow.registerTempTable('yellow')

/usr/local/lib/python3.12/dist-packages/pyspark/sql/classic/dataframe.py:178: FutureWarning: Deprecated in 2.0, use createOrReplaceTempView instead.
  warnings.warn("Deprecated in 2.0, use createOrReplaceTempView instead.", FutureWarning)

In [63]:
df_yellow_result = spark.sql(
    """
    SELECT
      PULocationID AS zone,
      date_trunc('hour', tpep_pickup_datetime) AS pickup_hour,
      SUM(total_amount) AS revenue_monthly_total_amount,
      COUNT(1) AS number_records
  FROM
      yellow
  WHERE tpep_pickup_datetime >= '2020-01-01 00:00:00'
  GROUP BY
      1, 2
  ORDER BY
      1, 2

    """
)

In [64]:
df_yellow_result.show()

+----+-------------------+----------------------------+--------------+
|zone|        pickup_hour|revenue_monthly_total_amount|number_records|
+----+-------------------+----------------------------+--------------+
|   1|2020-12-02 10:00:00|                       10.81|             1|
|   1|2020-12-03 11:00:00|                       72.92|             3|
|   1|2020-12-03 17:00:00|                       72.36|             1|
|   1|2020-12-04 14:00:00|                        70.3|             1|
|   1|2020-12-06 13:00:00|                        76.3|             1|
|   1|2020-12-07 03:00:00|                      114.36|             1|
|   1|2020-12-08 08:00:00|                       82.55|             1|
|   1|2020-12-08 13:00:00|                       68.46|             1|
|   1|2020-12-10 11:00:00|                      151.56|             1|
|   1|2020-12-10 16:00:00|                         0.3|             1|
|   1|2020-12-11 11:00:00|                        85.3|             1|
|   1|2020-12-11 14:00:00|                        96.6|             2|
|   1|2020-12-11 17:00:00|                        95.8|             1|
|   1|2020-12-12 13:00:00|                        80.3|             1|
|   1|2020-12-13 10:00:00|                       65.05|             1|
|   1|2020-12-13 16:00:00|                       74.55|             1|
|   1|2020-12-14 06:00:00|                        15.8|             1|
|   1|2020-12-14 07:00:00|                        85.3|             1|
|   1|2020-12-15 14:00:00|                        80.3|             1|
|   1|2020-12-15 20:00:00|                       158.3|             1|
+----+-------------------+----------------------------+--------------+
only showing top 20 rows

In [67]:
df_yellow_result \
.repartition(20) \
.write.parquet('data/report/revenue/yellow', mode='overwrite')

In [78]:
df_green_result_tmp = df_green_result \
  .withColumnRenamed('amount', 'green_amount') \
  .withColumnRenamed('number_records', 'green_number_records') \
  .withColumnRenamed('revenue_monthly_total_amount', 'green_monthly_revenue')

df_yellow_result_tmp = df_yellow_result \
          .withColumnRenamed('amount', 'yellow_amount') \
          .withColumnRenamed('number_records', 'yellow_number_records') \
          .withColumnRenamed('revenue_monthly_total_amount', 'yellow_monthly_revenue')

In [79]:
df_join = df_green_result_tmp.join(df_yellow_result_tmp, on=['pickup_hour', 'zone'], how='outer')

In [80]:
df_join.write.parquet('data/report/revenue/total', mode='overwrite')

In [81]:
df_join.show()

+-------------------+----+---------------------+--------------------+----------------------+---------------------+
|        pickup_hour|zone|green_monthly_revenue|green_number_records|yellow_monthly_revenue|yellow_number_records|
+-------------------+----+---------------------+--------------------+----------------------+---------------------+
|2020-12-02 10:00:00|   1|                 NULL|                NULL|                 10.81|                    1|
|2020-12-03 11:00:00|   1|                 NULL|                NULL|                 72.92|                    3|
|2020-12-04 14:00:00|   1|                 NULL|                NULL|                  70.3|                    1|
|2020-12-07 03:00:00|   1|                 NULL|                NULL|                114.36|                    1|
|2020-12-08 08:00:00|   1|                 NULL|                NULL|                 82.55|                    1|
|2020-12-08 13:00:00|   1|                 NULL|                NULL|                 68.46|                    1|
|2020-12-10 16:00:00|   1|                 NULL|                NULL|                   0.3|                    1|
|2020-12-11 11:00:00|   1|                 NULL|                NULL|                  85.3|                    1|
|2020-12-11 17:00:00|   1|                 NULL|                NULL|                  95.8|                    1|
|2020-12-12 13:00:00|   1|                 NULL|                NULL|                  80.3|                    1|
|2020-12-13 10:00:00|   1|                 NULL|                NULL|                 65.05|                    1|
|2020-12-13 16:00:00|   1|                 NULL|                NULL|                 74.55|                    1|
|2020-12-14 07:00:00|   1|                 NULL|                NULL|                  85.3|                    1|
|2020-12-17 12:00:00|   1|                 NULL|                NULL|                112.87|                    1|
|2020-12-17 13:00:00|   1|                 NULL|                NULL|                 70.02|                    3|
|2020-12-19 10:00:00|   1|                 NULL|                NULL|                339.45|                    3|
|2020-12-19 12:00:00|   1|                 NULL|                NULL|                 137.6|                    2|
|2020-12-19 14:00:00|   1|                 NULL|                NULL|                 110.3|                    1|
|2020-12-20 09:00:00|   1|                 NULL|                NULL|                  60.3|                    1|
|2020-12-20 10:00:00|   1|                 NULL|                NULL|                114.36|                    1|
+-------------------+----+---------------------+--------------------+----------------------+---------------------+
only showing top 20 rows

In [88]:
# Download Taxi Zones for Joins
!mkdir -p data/zones

# lookup_taxi_zones
!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv -O data/zones/taxi_zone_lookup.csv

--2026-03-08 15:08:36--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A46%3A11Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A46%3A11Z&ske=2026-03-08T15%3A46%3A11Z&sks=b&skv=2018-11-09&sig=3jFHrldrz3WXz2ls9LdVoiZayDBYAFKyF51v%2B1iYahY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MjgxNiwibmJmIjoxNzcyOTgyNTE2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.-r-T5GLKcAZmkbD48c1ad-6BjADJ5YGUuu8ydAXDmGY&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream [following]
--2026-03-08 15:08:36--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-08T15%3A46%3A11Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-08T14%3A46%3A11Z&ske=2026-03-08T15%3A46%3A11Z&sks=b&skv=2018-11-09&sig=3jFHrldrz3WXz2ls9LdVoiZayDBYAFKyF51v%2B1iYahY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mjk4MjgxNiwibmJmIjoxNzcyOTgyNTE2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.-r-T5GLKcAZmkbD48c1ad-6BjADJ5YGUuu8ydAXDmGY&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12322 (12K) [application/octet-stream]
Saving to: ‘data/zones/taxi_zone_lookup.csv’

data/zones/taxi_zon 100%[===================>]  12.03K  --.-KB/s    in 0s

2026-03-08 15:08:36 (82.5 MB/s) - ‘data/zones/taxi_zone_lookup.csv’ saved [12322/12322]

In [89]:
df_zones = spark.read \
      .option("header", "true") \
      .csv('data/zones/taxi_zone_lookup.csv')

In [90]:
df_zones_final = df_yellow_result_tmp.join(df_zones, df_yellow_result_tmp.zone == df_zones.LocationID)

In [94]:
df_zones_final.drop('LocationID', 'zone').write.parquet('data/zones', mode='overwrite')

In [100]:
df_zones_final.explain()

== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- BroadcastHashJoin [cast(zone#632 as bigint)], [cast(LocationID#869 as bigint)], Inner, BuildRight, false
   :- HashAggregate(keys=[PULocationID#103, _groupingexpression#1007], functions=[sum(total_amount#112), count(1)])
   :  +- Exchange hashpartitioning(PULocationID#103, _groupingexpression#1007, 200), ENSURE_REQUIREMENTS, [plan_id=3405]
   :     +- HashAggregate(keys=[PULocationID#103, _groupingexpression#1007], functions=[partial_sum(total_amount#112), partial_count(1)])
   :        +- Project [PULocationID#103, total_amount#112, date_trunc(hour, tpep_pickup_datetime#97, Some(Etc/UTC)) AS _groupingexpression#1007]
   :           +- Filter ((isnotnull(tpep_pickup_datetime#97) AND (tpep_pickup_datetime#97 >= 2020-01-01 00:00:00)) AND isnotnull(PULocationID#103))
   :              +- FileScan csv [tpep_pickup_datetime#97,PULocationID#103,total_amount#112] Batched: false, DataFilters: [isnotnull(tpep_pickup_datetime#97), (tpep_pickup_datetime#97 >= 2020-01-01 00:00:00), isnotnull(..., Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/content/data/raw/yellow/2020/12], PartitionFilters: [], PushedFilters: [IsNotNull(tpep_pickup_datetime), GreaterThanOrEqual(tpep_pickup_datetime,2020-01-01 00:00:00.0),..., ReadSchema: struct<tpep_pickup_datetime:timestamp,PULocationID:int,total_amount:double>
   +- BroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, string, false] as bigint)),false), [plan_id=3408]
      +- Filter isnotnull(LocationID#869)
         +- FileScan csv [LocationID#869,Borough#870,Zone#871,service_zone#872] Batched: false, DataFilters: [isnotnull(LocationID#869)], Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/content/data/zones/taxi_zone_lookup.csv], PartitionFilters: [], PushedFilters: [IsNotNull(LocationID)], ReadSchema: struct<LocationID:string,Borough:string,Zone:string,service_zone:string>

# Resilient Distribution Datasets (RDD)

In [105]:
df_green.rdd.take(10)

[Row(VendorID=2, lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 29, 37), lpep_dropoff_datetime=datetime.datetime(2020, 12, 1, 0, 32, 51), store_and_fwd_flag='N', RatecodeID=1, PULocationID=75, DOLocationID=75, passenger_count=1, trip_distance=0.59, fare_amount=4.5, extra=0.5, mta_tax=0.5, tip_amount=1.16, tolls_amount=0.0, ehail_fee=None, improvement_surcharge=0.3, total_amount=6.96, payment_type=1, trip_type=1, congestion_surcharge=0.0),
 Row(VendorID=2, lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 41, 46), lpep_dropoff_datetime=datetime.datetime(2020, 12, 1, 0, 46, 31), store_and_fwd_flag='N', RatecodeID=1, PULocationID=75, DOLocationID=74, passenger_count=1, trip_distance=1.24, fare_amount=6.0, extra=0.5, mta_tax=0.5, tip_amount=1.46, tolls_amount=0.0, ehail_fee=None, improvement_surcharge=0.3, total_amount=8.76, payment_type=1, trip_type=1, congestion_surcharge=0.0),
 Row(VendorID=2, lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 5, 46), lpep_dropoff_datetime=datetime.datetime(2020, 12, 1, 0, 10, 48), store_and_fwd_flag='N', RatecodeID=1, PULocationID=244, DOLocationID=243, passenger_count=2, trip_distance=1.19, fare_amount=6.0, extra=0.5, mta_tax=0.5, tip_amount=1.46, tolls_amount=0.0, ehail_fee=None, improvement_surcharge=0.3, total_amount=8.76, payment_type=1, trip_type=1, congestion_surcharge=0.0),
 Row(VendorID=2, lpep_pickup_datetime=datetime.datetime(2020, 11, 30, 23, 59, 17), lpep_dropoff_datetime=datetime.datetime(2020, 12, 1, 0, 16, 6), store_and_fwd_flag='N', RatecodeID=1, PULocationID=75, DOLocationID=68, passenger_count=1, trip_distance=5.08, fare_amount=17.0, extra=0.5, mta_tax=0.5, tip_amount=2.0, tolls_amount=0.0, ehail_fee=None, improvement_surcharge=0.3, total_amount=23.05, payment_type=1, trip_type=1, congestion_surcharge=2.75),
 Row(VendorID=2, lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 57, 3), lpep_dropoff_datetime=datetime.datetime(2020, 12, 1, 1, 0, 29), store_and_fwd_flag='N', RatecodeID=1, PULocationID=74, DOLocationID=263, passenger_count=1, trip_distance=1.24, fare_amount=5.5, extra=0.5, mta_tax=0.5, tip_amount=0.0, tolls_amount=0.0, ehail_fee=None, improvement_surcharge=0.3, total_amount=9.55, payment_type=2, trip_type=1, congestion_surcharge=2.75),
 Row(VendorID=2, lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 5, 38), lpep_dropoff_datetime=datetime.datetime(2020, 12, 1, 0, 20, 26), store_and_fwd_flag='N', RatecodeID=1, PULocationID=244, DOLocationID=74, passenger_count=1, trip_distance=2.81, fare_amount=12.5, extra=0.5, mta_tax=0.5, tip_amount=0.0, tolls_amount=0.0, ehail_fee=None, improvement_surcharge=0.3, total_amount=13.8, payment_type=2, trip_type=1, congestion_surcharge=0.0),
 Row(VendorID=2, lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 21, 19), lpep_dropoff_datetime=datetime.datetime(2020, 12, 1, 0, 26, 48), store_and_fwd_flag='N', RatecodeID=1, PULocationID=69, DOLocationID=116, passenger_count=1, trip_distance=1.12, fare_amount=6.0, extra=0.5, mta_tax=0.5, tip_amount=0.0, tolls_amount=0.0, ehail_fee=None, improvement_surcharge=0.3, total_amount=7.3, payment_type=2, trip_type=1, congestion_surcharge=0.0),
 Row(VendorID=2, lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 33, 46), lpep_dropoff_datetime=datetime.datetime(2020, 12, 1, 0, 44, 1), store_and_fwd_flag='N', RatecodeID=1, PULocationID=116, DOLocationID=247, passenger_count=1, trip_distance=2.27, fare_amount=9.5, extra=0.5, mta_tax=0.5, tip_amount=0.0, tolls_amount=0.0, ehail_fee=None, improvement_surcharge=0.3, total_amount=10.8, payment_type=2, trip_type=1, congestion_surcharge=0.0),
 Row(VendorID=2, lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 5, 28), lpep_dropoff_datetime=datetime.datetime(2020, 12, 1, 0, 20, 28), store_and_fwd_flag='N', RatecodeID=1, PULocationID=75, DOLocationID=213, passenger_count=1, trip_distance=6.67, fare_amount=20.0, extra=0.5, mta_tax=0.5, tip_amount=0.0, tolls_amount=0.0, ehail_fee=None, improvement_surcharge=0.3, total_amount=21.3, payment_type=2, trip_type=1, congestion_surcharge=0.0),
 Row(VendorID=2, lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 36, 58), lpep_dropoff_datetime=datetime.datetime(2020, 12, 1, 0, 40, 31), store_and_fwd_flag='N', RatecodeID=1, PULocationID=75, DOLocationID=74, passenger_count=1, trip_distance=0.95, fare_amount=5.0, extra=0.5, mta_tax=0.5, tip_amount=0.0, tolls_amount=0.0, ehail_fee=None, improvement_surcharge=0.3, total_amount=6.3, payment_type=2, trip_type=1, congestion_surcharge=0.0)]

In [109]:
rdd = df_green \
      .select('lpep_pickup_datetime', 'PULocationID', 'total_amount') \
      .rdd

In [110]:
rdd.take(5)

[Row(lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 29, 37), PULocationID=75, total_amount=6.96),
 Row(lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 41, 46), PULocationID=75, total_amount=8.76),
 Row(lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 5, 46), PULocationID=244, total_amount=8.76),
 Row(lpep_pickup_datetime=datetime.datetime(2020, 11, 30, 23, 59, 17), PULocationID=75, total_amount=23.05),
 Row(lpep_pickup_datetime=datetime.datetime(2020, 12, 1, 0, 57, 3), PULocationID=74, total_amount=9.55)]

In [111]:
from datetime import datetime

In [134]:
start = datetime(year=2020, month=1, day=1)

def filter_outliers(row):
  return row.lpep_pickup_datetime >= start

In [135]:
rows = rdd.take(10)
row = rows[0]

In [117]:
row.lpep_pickup_datetime.replace(minute=0, second=0, microsecond=0)

datetime.datetime(2020, 12, 1, 0, 0)

In [136]:
def prepare_grouping(row):
  hour = row.lpep_pickup_datetime.replace(minute=0, second=0, microsecond=0)
  zone = row.PULocationID
  key = (hour, zone)

  amount = row.total_amount
  count = 1
  value = (amount, count)

  return (key, value)

In [141]:
def calculate_revenue(left_value, right_value):
  left_amount, left_count = left_value
  right_amount, right_count = right_value

  output_amount = left_amount + right_amount
  output_count = left_count + right_count
  output_value = (output_amount, output_count)

  return (output_amount, output_count)

In [142]:
from collections import namedtuple

In [143]:
RevenueRow = namedtuple('RevenueRow', ['hour', 'zone', 'revenue', 'count'])

In [144]:
def unwrap(row):
  return RevenueRow (
      hour = row[0][0],
      zone = row[0][1],
      revenue = row[1][0],
      count = row[1][1])

In [150]:
from pyspark.sql import types

In [151]:
df_rdd_schema = types.StructType([
     types.StructField('hour', types.TimestampType(), True),
     types.StructField('zone', types.IntegerType(), True),
     types.StructField('revenue', types.DoubleType(), True),
     types.StructField('count', types.IntegerType(), True)
     ])

In [156]:
df_rdd_result = rdd \
  .filter(filter_outliers) \
  .map(prepare_grouping) \
  .reduceByKey(calculate_revenue) \
  .map(unwrap) \
  .toDF(df_rdd_schema)

In [157]:
df_rdd_result.show()

+-------------------+----+------------------+-----+
|               hour|zone|           revenue|count|
+-------------------+----+------------------+-----+
|2020-12-01 00:00:00|  75|             80.35|    6|
|2020-12-01 00:00:00| 244|22.560000000000002|    2|
|2020-11-30 23:00:00|  75|             23.05|    1|
|2020-12-01 00:00:00|  74|              9.55|    1|
|2020-12-01 00:00:00|  69|               7.3|    1|
|2020-12-01 00:00:00| 116|              10.8|    1|
|2020-12-01 00:00:00|  41|             41.96|    3|
|2020-12-01 00:00:00| 130|              38.1|    2|
|2020-12-01 01:00:00|   7|              9.96|    1|
|2020-12-01 01:00:00| 116|              85.6|    2|
|2020-12-01 00:00:00| 119|             66.42|    2|
|2020-12-01 01:00:00|  74|               5.3|    1|
|2020-12-01 01:00:00|  42|             28.26|    1|
|2020-12-01 01:00:00| 166|               4.3|    1|
|2020-12-01 01:00:00|  41|              22.1|    2|
|2020-12-01 01:00:00| 236|              19.3|    1|
|2020-12-01 01:00:00|  75|             10.56|    1|
|2020-12-01 01:00:00| 232|              40.0|    1|
|2020-12-01 02:00:00|  74|             54.69|    2|
|2020-12-01 02:00:00|  75|               9.8|    1|
+-------------------+----+------------------+-----+
only showing top 20 rows

In [158]:
# Save to parquet
df_rdd_result.write.parquet('tmp/green-revenue')

In [159]:
spark.read.parquet('tmp/green-revenue')

DataFrame[hour: timestamp, zone: int, revenue: double, count: int]

### RDD mapPartition

In [160]:
# Scenario: A service that predicts the duration of a trip (ML Model)

columns = ['VendorID', 'lpep_pickup_datetime', 'PULocationID', 'DOLocationID', 'trip_distance']

duration_rdd = df_green \
    .select(columns) \
    .rdd

In [173]:
import pandas as pd

In [174]:
rows = duration_rdd.take(10)

In [175]:
pd.DataFrame(rows, columns=columns)

   VendorID lpep_pickup_datetime  PULocationID  DOLocationID  trip_distance
0         2  2020-12-01 00:29:37            75            75           0.59
1         2  2020-12-01 00:41:46            75            74           1.24
2         2  2020-12-01 00:05:46           244           243           1.19
3         2  2020-11-30 23:59:17            75            68           5.08
4         2  2020-12-01 00:57:03            74           263           1.24
5         2  2020-12-01 00:05:38           244            74           2.81
6         2  2020-12-01 00:21:19            69           116           1.12
7         2  2020-12-01 00:33:46           116           247           2.27
8         2  2020-12-01 00:05:28            75           213           6.67
9         2  2020-12-01 00:36:58            75            74           0.95

In [178]:
def apply_model_batch(rows):
  df = pd.DataFrame(rows, columns=columns)
  cnt = len(df)

  return [cnt]

In [180]:
duration_rdd.mapPartitions(apply_model_batch).collect()

[83130]